# Travis config
before_install:
  - wget https://ftp.mozilla.org/pub/mozilla.org/labs/jetpack/jetpack-sdk-latest.tar.gz
  - tar -xzf jetpack-sdk-latest.tar.gz
  - cd addon-sdk*
  - source bin/activate
  - cd ..
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -extension RANDR -screen 0 1280x1024x16"

script: cfx --verbose test
